In [1]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM team_profile'
team_profile_df = pd.read_sql_query(query, conn)
conn.close()

pd.set_option('display.max_columns', None)
team_profile_df.head()

,season_end_year,team_id,team_name,gp,w,l,w_pct,off_rating,ast_pct,pct_uast_fgm,ts_pct,league_off_rating,league_ast_pct,league_pct_uast_fgm,league_ts_pct,team_orating_plus,team_ts_plus,team_possession_residual,team_possession_plus,oreb_pct,tm_tov_pct,team_orating_plus_rank,team_ts_plus_rank,team_possession_plus_rank,pct_uast_fgm_rank,oreb_pct_rank,tm_tov_pct_rank,team_fg_pct,team_3pt_pct,team_ft_pct,team_ppg,finishers,balanced,creators,finishers_q,balanced_q,creators_q
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,96.9,0.542,0.458,0.500,101.555172,0.610069,0.389931,0.518034,95.416115,96.518671,-1.713859,98.286141,0.313,0.178,27,26,25,29,15,28,0.431,0.357,0.759,91.0,7,4,5,0,2,2
1,2001,1610612738,Boston Celtics,82,36,46,0.439,100.1,0.616,0.384,0.521,101.555172,0.610069,0.389931,0.518034,98.567111,100.572456,-1.904824,98.095176,0.280,0.166,17,12,27,12,26,20,0.428,0.363,0.740,94.6,8,3,4,2,2,1
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,99.7,0.679,0.321,0.506,101.555172,0.610069,0.389931,0.518034,98.173237,97.676895,0.088417,100.088417,0.315,0.156,19,23,13,2,13,10,0.431,0.346,0.745,91.9,12,2,1,3,1,1
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,95.9,0.665,0.335,0.495,101.555172,0.610069,0.389931,0.518034,94.431428,95.553485,-1.902840,98.097160,0.302,0.173,29,28,26,3,20,25,0.424,0.346,0.739,87.6,7,6,3,3,2,0
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,99.3,0.591,0.409,0.509,101.555172,0.610069,0.389931,0.518034,97.779362,98.256007,-0.782881,99.217119,0.331,0.177,22,22,20,19,7,27,0.442,0.334,0.765,92.2,6,5,7,1,3,2

In [4]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM player_profile'
player_profile_df = pd.read_sql_query(query, conn)
conn.close()

player_profile_df.head()

,player_name,team_name,team_abbreviation,team_id,season_end_year,season,slug,player_id,games_played,minutes_per_game,minutes_played,scoring_plus,pts_plus,ts_plus,per_100_pts,true_shooting_percentage,age,positions,points_per_game,fg_percentage,three_point_percentage,ft_percentage,assists_per_game,offensive_rebounds_per_game,defensive_rebounds_per_game,total_rebounds_per_game,turnovers_per_game,steals_per_game,blocks_per_game,stocks_per_game,per_100_reb,per_100_ast,per_100_stl,per_100_blk,per_100_tov,qualified,qualified_ast,pct_uast_fgm,uast_bin,uast_rating,profile
0,A.C. Green,MIAMI HEAT,MIA,1610612748,2001,2000-2001,greenac01,920,82,17.207317,1411,89.438042,67.943364,94.980695,13.8,0.492,37,POWER FORWARD,4.475610,0.444444,0.000000,0.711712,0.475610,1.304878,2.512195,3.817073,0.548780,0.365854,0.097561,0.463415,11.8,1.5,1.1,0.3,1.7,0,0,0.236,1,-4,Finisher
1,A.J. Guyton,CHICAGO BULLS,CHI,1610612741,2001,2000-2001,guytoaj01,2062,33,19.090909,630,93.027308,83.206003,95.559846,16.9,0.495,22,POINT GUARD,6.000000,0.406250,0.391304,0.833333,1.939394,0.303030,0.787879,1.090909,0.727273,0.272727,0.151515,0.424242,3.1,5.5,0.8,0.4,2.0,0,0,0.308,2,-3,Finisher
2,Aaron McKie,PHILADELPHIA 76ERS,PHI,1610612755,2001,2000-2001,mckieaa01,243,76,31.500000,2394,103.333560,93.052867,105.984556,18.9,0.549,28,SHOOTING GUARD,11.552632,0.473389,0.311765,0.768041,4.960526,0.434211,3.657895,4.092105,2.671053,1.394737,0.105263,1.500000,6.7,8.1,2.3,0.2,4.4,1,1,0.447,6,1,Balanced
3,Aaron Williams,NEW JERSEY NETS,NJN,1610612751,2001,2000-2001,williaa01,1425,82,28.487805,2336,100.474240,91.083495,102.895753,18.5,0.533,29,POWER FORWARD,10.219512,0.456923,0.000000,0.787097,1.073171,2.573171,4.621951,7.195122,1.609756,0.719512,1.378049,2.097561,13.0,1.9,1.3,2.5,2.9,1,0,0.377,5,0,Balanced
4,Adam Keefe,GOLDEN STATE WARRIORS,GSW,1610612744,2001,2000-2001,keefead01,228,67,12.477612,836,79.257673,49.726665,86.872587,10.1,0.450,30,POWER FORWARD,2.507463,0.402516,0.333333,0.619048,0.537313,1.343284,1.776119,3.119403,0.597015,0.417910,0.298507,0.716418,12.5,2.2,1.7,1.2,2.4,0,0,0.313,3,-2,Finisher