In [1]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM team_advanced_stats'
team_advanced_stats_df = pd.read_sql_query(query, conn)
conn.close()

pd.set_option('display.max_columns', None)
team_advanced_stats_df

,season_end_year,team_id,team_name,gp,w,l,w_pct,min,e_off_rating,off_rating,e_def_rating,def_rating,e_net_rating,net_rating,ast_pct,ast_to,ast_ratio,oreb_pct,dreb_pct,reb_pct,tm_tov_pct,efg_pct,ts_pct,e_pace,pace,pace_per40,poss,pie,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,off_rating_rank,def_rating_rank,net_rating_rank,ast_pct_rank,ast_to_rank,ast_ratio_rank,oreb_pct_rank,dreb_pct_rank,reb_pct_rank,tm_tov_pct_rank,efg_pct_rank,ts_pct_rank,pace_rank,pie_rank
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,3946.0,95.6,96.9,101.9,102.4,-6.3,-5.5,0.542,1.14,14.9,0.313,0.691,0.501,0.178,0.456,0.500,94.5,93.63,78.02,7695,0.452,1,25,25,25,27,27,17,25,29,29,29,15,12,14,28,25,26,11,26
1,2001,1610612738,Boston Celtics,82,36,46,0.439,3966.0,99.0,100.1,100.9,102.3,-1.9,-2.2,0.616,1.33,16.2,0.280,0.690,0.478,0.166,0.473,0.521,95.0,93.81,78.17,7748,0.468,1,20,20,20,13,17,15,20,12,21,19,26,15,28,20,14,12,10,23
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,3976.0,99.3,99.7,96.3,97.6,3.0,2.1,0.679,1.61,17.8,0.315,0.710,0.513,0.156,0.457,0.506,92.0,91.24,76.04,7565,0.527,1,14,14,14,8,19,6,14,2,6,7,14,1,6,10,24,23,21,7
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,3971.0,94.3,95.9,104.9,105.9,-10.6,-10.0,0.665,1.40,17.4,0.302,0.673,0.480,0.173,0.450,0.495,91.7,90.47,75.39,7486,0.432,1,29,29,29,10,29,28,29,3,18,9,20,27,27,25,28,28,27,28
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,3966.0,97.4,99.3,102.0,103.5,-4.6,-4.2,0.591,1.27,16.2,0.331,0.678,0.505,0.177,0.459,0.509,93.9,92.32,76.94,7613,0.469,1,23,23,23,17,22,21,23,20,25,20,7,23,10,27,23,22,17,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2026,1610612758,Sacramento Kings,82,22,60,0.268,3951.0,109.0,110.6,118.0,120.3,-9.0,-9.7,0.615,1.78,18.2,0.298,0.685,0.487,0.143,0.525,0.560,101.8,100.12,83.43,8233,0.455,1,26,26,26,14,26,28,28,20,19,21,17,23,25,15,29,29,17,28
772,2026,1610612759,San Antonio Spurs,82,62,20,0.756,3946.0,116.6,118.7,108.5,110.4,8.1,8.4,0.646,2.09,19.5,0.306,0.724,0.521,0.133,0.559,0.595,102.5,100.72,83.93,8275,0.542,1,2,2,2,26,3,3,3,13,5,7,10,1,6,5,7,5,12,3
773,2026,1610612761,Toronto Raptors,82,46,36,0.561,3956.0,113.0,115.0,110.0,112.1,2.9,2.9,0.692,2.16,20.5,0.300,0.693,0.496,0.137,0.546,0.581,101.0,99.22,82.68,8177,0.522,1,11,11,11,13,15,5,11,3,2,1,16,16,15,7,16,15,21,8
774,2026,1610612762,Utah Jazz,82,22,60,0.268,3966.0,111.2,112.7,119.3,120.8,-8.0,-8.2,0.696,1.91,19.9,0.298,0.693,0.492,0.149,0.536,0.575,104.9,103.54,86.28,8558,0.464,1,26,26,26,6,22,29,27,2,10,5,18,17,19,22,20,20,2,27
775,2026,1610612764,Washington Wizards,82,17,65,0.207,3951.0,108.2,109.7,119.6,121.5,-11.4,-11.8,0.599,1.60,17.6,0.285,0.664,0.471,0.152,0.535,0.566,104.0,102.49,85.41,8442,0.433,1,30,30,30,25,29,30,30,24,28,27,23,29,30,24,21,27,6,30

In [4]:
conn = sqlite3.connect('nba_stats.db')

query = 'SELECT * FROM nba_advanced_averages'
nba_advanced_averages_df = pd.read_sql_query(query, conn)
conn.close()

nba_advanced_averages_df

,season_end_year,min,e_off_rating,off_rating,e_def_rating,def_rating,e_net_rating,net_rating,ast_pct,ast_to,ast_ratio,oreb_pct,dreb_pct,reb_pct,tm_tov_pct,efg_pct,ts_pct,e_pace,pace,pace_per40,poss,pie
0,2001,3969.103448,100.234483,101.555172,100.220690,101.544828,1.379310e-02,1.034483e-02,0.610069,1.455517,16.813793,0.311621,0.688034,0.500034,0.161207,0.473069,0.518034,93.800000,92.584138,77.153448,7655.517241,0.500069
1,2002,3963.241379,101.575862,103.093103,101.603448,103.110345,-1.379310e-02,-1.379310e-02,0.606069,1.525517,16.982759,0.317069,0.682690,0.500034,0.156207,0.477034,0.520276,93.344828,91.957241,76.630345,7592.586207,0.499931
2,2003,3968.344828,100.706897,102.162069,100.703448,102.158621,1.724138e-02,-6.896552e-03,0.601690,1.456552,16.658621,0.314207,0.686034,0.500034,0.160310,0.473759,0.519172,93.637931,92.300345,76.915862,7630.758621,0.499448
3,2004,3963.931034,100.031034,101.393103,100.017241,101.372414,2.068966e-02,2.413793e-02,0.608172,1.436897,16.665517,0.316655,0.683103,0.500069,0.162655,0.471034,0.516103,92.700000,91.450000,76.208621,7551.862069,0.500172
4,2005,3966.666667,103.063333,104.506667,103.073333,104.510000,-6.666667e-03,-6.666667e-03,0.592233,1.475000,16.543333,0.318300,0.681933,0.500200,0.156033,0.482233,0.529400,93.560000,92.274333,76.895333,7625.166667,0.499900
5,2006,3970.333333,103.410000,104.856667,103.406667,104.846667,3.700743e-17,6.666667e-03,0.575067,1.441667,16.270000,0.306067,0.693733,0.500100,0.155900,0.489800,0.535533,92.993333,91.704667,76.419667,7585.533333,0.499933
6,2007,3971.666667,103.720000,105.276667,103.706667,105.263333,3.333333e-03,1.333333e-02,0.582200,1.415333,16.566667,0.304267,0.695800,0.500100,0.161333,0.496167,0.541433,94.330000,92.931000,77.443333,7689.300000,0.500067
7,2008,3960.666667,104.730000,106.196667,104.720000,106.190000,1.000000e-02,2.000000e-02,0.583500,1.552667,16.820000,0.301367,0.698367,0.500100,0.149900,0.497400,0.540233,94.790000,93.485000,77.904000,7713.800000,0.499867
8,2009,3964.333333,105.446667,106.983333,105.396667,106.940000,4.333333e-02,4.333333e-02,0.565133,1.504000,16.416667,0.302567,0.697600,0.500000,0.150100,0.499833,0.544400,94.116667,92.757333,77.298333,7660.800000,0.500533
9,2010,3963.333333,104.900000,106.583333,104.863333,106.553333,2.000000e-02,2.333333e-02,0.563433,1.502000,16.480000,0.301267,0.698667,0.500133,0.150900,0.500933,0.542967,95.093333,93.599000,78.000000,7728.233333,0.500400
10,2011,3967.000000,104.486667,106.313333,104.440000,106.276667,3.666667e-02,4.000000e-02,0.577200,1.517333,16.746667,0.301567,0.697767,0.499900,0.152167,0.498533,0.541533,94.536667,92.898000,77.415667,7677.666667,0.500367
11,2012,3193.666667,101.830000,103.496667,101.836667,103.493333,2.960595e-17,-1.000000e-02,0.575267,1.449667,16.410000,0.305867,0.693700,0.500033,0.156767,0.487300,0.527033,93.756667,92.249333,76.873667,6137.733333,0.499933
12,2013,3963.133333,103.106667,104.760000,103.130000,104.766667,-1.000000e-02,-3.333333e-03,0.595867,1.523667,17.103333,0.302667,0.696667,0.500000,0.155300,0.496633,0.534667,94.426667,92.944000,77.454333,7674.100000,0.500000
13,2014,3968.000000,104.006667,105.683333,104.006667,105.690000,-1.110223e-17,3.333333e-03,0.583467,1.508333,16.810000,0.293667,0.705533,0.499867,0.153333,0.501267,0.541000,96.336667,94.799333,78.999667,7836.433333,0.500067
14,2015,3968.000000,103.006667,104.740000,103.036667,104.746667,-2.000000e-02,-2.666667e-02,0.586967,1.548333,16.810000,0.291933,0.707800,0.499933,0.150400,0.495967,0.534133,96.310000,94.715000,78.929333,7829.866667,0.499400
15,2016,3965.666667,103.906667,105.560000,103.890000,105.536667,1.000000e-02,6.666667e-03,0.582033,1.557333,16.813333,0.278767,0.721200,0.500100,0.147833,0.502500,0.541300,98.083333,96.540667,80.451333,7975.866667,0.499833
16,2017,3962.666667,106.240000,108.156667,106.210000,108.143333,1.666667e-02,2.000000e-02,0.579067,1.631667,17.006667,0.275567,0.724233,0.499900,0.142800,0.513833,0.552400,98.723333,96.962000,80.802667,8004.766667,0.499700
17,2018,3959.000000,106.173333,107.840000,106.180000,107.840000,-1.000000e-02,7.771561e-17,0.586367,1.633333,17.263333,0.267300,0.732600,0.499933,0.144633,0.521267,0.556200,99.563333,98.028667,81.690333,8085.333333,0.499767
18,2019,3963.000000,107.853333,109.720000,107.856667,109.730000,-6.666667e-03,-6.666667e-03,0.597933,1.752667,17.610000,0.271333,0.728167,0.499967,0.138933,0.524167,0.559567,102.390000,100.660333,83.883667,8310.833333,0.499867
19,2020,3413.800000,107.970000,109.983333,108.153333,110.153333,-1.800000e-01,-1.700000e-01,0.597100,1.679333,17.513333,0.267767,0.731733,0.499700,0.143333,0.528333,0.564267,102.680000,100.794667,83.995667,7169.533333,0.499067
20,2021,3476.666667,109.876667,111.713333,109.860000,111.696667,2.000000e-02,1.333333e-02,0.601833,1.802667,17.983333,0.264300,0.735667,0.500100,0.137833,0.537933,0.571800,101.420000,99.750000,83.124667,7224.900000,0.499833
21,2022,3958.333333,109.370000,111.383333,109.346667,111.360000,1.000000e-02,1.333333e-02,0.606533,1.799000,17.940000,0.274600,0.725100,0.500033,0.138567,0.531733,0.566167,100.576667,98.754333,82.295333,8143.800000,0.500100
22,2023,3965.666667,112.106667,114.076667,112.086667,114.070000,2.000000e-02,2.000000e-02,0.602933,1.803667,18.166667,0.280133,0.719033,0.499900,0.140133,0.545467,0.581500,101.553333,99.791667,83.159000,8244.433333,0.499967
23,2024,3958.333333,112.516667,114.546667,112.493333,114.516667,3.333333e-02,3.666667e-02,0.632300,1.971667,19.036667,0.283200,0.716567,0.499967,0.136500,0.546500,0.579967,100.933333,99.149667,82.624000,8176.400000,0.499967
24,2025,3957.333333,111.636667,113.680000,111.630000,113.683333,1.333333e-02,0.000000e+00,0.636667,1.869667,18.810000,0.292733,0.706533,0.499867,0.142767,0.543033,0.576200,101.400000,99.579667,82.982667,8209.633333,0.499767
25,2026,3956.666667,112.750000,114.786667,112.706667,114.733333,4.000000e-02,5.333333e-02,0.637233,1.854333,18.773333,0.304933,0.694667,0.500000,0.144100,0.545667,0.581433,102.020000,100.216667,83.513333,8260.900000,0.500400

In [5]:
conn = sqlite3.connect('nba_stats.db')

query = '''
SELECT t.*, n.off_rating AS league_off_rating, n.ast_pct AS league_ast_pct, n.ts_pct AS league_ts_pct
FROM team_advanced_stats AS t
JOIN nba_advanced_averages AS n ON t.season_end_year = n.season_end_year
'''

team_league_advanced_df = pd.read_sql_query(query, conn)
conn.close()

team_league_advanced_df

,season_end_year,team_id,team_name,gp,w,l,w_pct,min,e_off_rating,off_rating,e_def_rating,def_rating,e_net_rating,net_rating,ast_pct,ast_to,ast_ratio,oreb_pct,dreb_pct,reb_pct,tm_tov_pct,efg_pct,ts_pct,e_pace,pace,pace_per40,poss,pie,gp_rank,w_rank,l_rank,w_pct_rank,min_rank,off_rating_rank,def_rating_rank,net_rating_rank,ast_pct_rank,ast_to_rank,ast_ratio_rank,oreb_pct_rank,dreb_pct_rank,reb_pct_rank,tm_tov_pct_rank,efg_pct_rank,ts_pct_rank,pace_rank,pie_rank,league_off_rating,league_ast_pct,league_ts_pct
0,2001,1610612737,Atlanta Hawks,82,25,57,0.305,3946.0,95.6,96.9,101.9,102.4,-6.3,-5.5,0.542,1.14,14.9,0.313,0.691,0.501,0.178,0.456,0.500,94.5,93.63,78.02,7695,0.452,1,25,25,25,27,27,17,25,29,29,29,15,12,14,28,25,26,11,26,101.555172,0.610069,0.518034
1,2001,1610612738,Boston Celtics,82,36,46,0.439,3966.0,99.0,100.1,100.9,102.3,-1.9,-2.2,0.616,1.33,16.2,0.280,0.690,0.478,0.166,0.473,0.521,95.0,93.81,78.17,7748,0.468,1,20,20,20,13,17,15,20,12,21,19,26,15,28,20,14,12,10,23,101.555172,0.610069,0.518034
2,2001,1610612766,Charlotte Hornets,82,46,36,0.561,3976.0,99.3,99.7,96.3,97.6,3.0,2.1,0.679,1.61,17.8,0.315,0.710,0.513,0.156,0.457,0.506,92.0,91.24,76.04,7565,0.527,1,14,14,14,8,19,6,14,2,6,7,14,1,6,10,24,23,21,7,101.555172,0.610069,0.518034
3,2001,1610612741,Chicago Bulls,82,15,67,0.183,3971.0,94.3,95.9,104.9,105.9,-10.6,-10.0,0.665,1.40,17.4,0.302,0.673,0.480,0.173,0.450,0.495,91.7,90.47,75.39,7486,0.432,1,29,29,29,10,29,28,29,3,18,9,20,27,27,25,28,28,27,28,101.555172,0.610069,0.518034
4,2001,1610612739,Cleveland Cavaliers,82,30,52,0.366,3966.0,97.4,99.3,102.0,103.5,-4.6,-4.2,0.591,1.27,16.2,0.331,0.678,0.505,0.177,0.459,0.509,93.9,92.32,76.94,7613,0.469,1,23,23,23,17,22,21,23,20,25,20,7,23,10,27,23,22,17,22,101.555172,0.610069,0.518034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,2026,1610612758,Sacramento Kings,82,22,60,0.268,3951.0,109.0,110.6,118.0,120.3,-9.0,-9.7,0.615,1.78,18.2,0.298,0.685,0.487,0.143,0.525,0.560,101.8,100.12,83.43,8233,0.455,1,26,26,26,14,26,28,28,20,19,21,17,23,25,15,29,29,17,28,114.786667,0.637233,0.581433
772,2026,1610612759,San Antonio Spurs,82,62,20,0.756,3946.0,116.6,118.7,108.5,110.4,8.1,8.4,0.646,2.09,19.5,0.306,0.724,0.521,0.133,0.559,0.595,102.5,100.72,83.93,8275,0.542,1,2,2,2,26,3,3,3,13,5,7,10,1,6,5,7,5,12,3,114.786667,0.637233,0.581433
773,2026,1610612761,Toronto Raptors,82,46,36,0.561,3956.0,113.0,115.0,110.0,112.1,2.9,2.9,0.692,2.16,20.5,0.300,0.693,0.496,0.137,0.546,0.581,101.0,99.22,82.68,8177,0.522,1,11,11,11,13,15,5,11,3,2,1,16,16,15,7,16,15,21,8,114.786667,0.637233,0.581433
774,2026,1610612762,Utah Jazz,82,22,60,0.268,3966.0,111.2,112.7,119.3,120.8,-8.0,-8.2,0.696,1.91,19.9,0.298,0.693,0.492,0.149,0.536,0.575,104.9,103.54,86.28,8558,0.464,1,26,26,26,6,22,29,27,2,10,5,18,17,19,22,20,20,2,27,114.786667,0.637233,0.581433
775,2026,1610612764,Washington Wizards,82,17,65,0.207,3951.0,108.2,109.7,119.6,121.5,-11.4,-11.8,0.599,1.60,17.6,0.285,0.664,0.471,0.152,0.535,0.566,104.0,102.49,85.41,8442,0.433,1,30,30,30,25,29,30,30,24,28,27,23,29,30,24,21,27,6,30,114.786667,0.637233,0.581433

In [6]:
team_league_advanced_df['pts_plus'] = (team_league_advanced_df['off_rating'] / team_league_advanced_df['league_off_rating']) * 100
team_league_advanced_df['ts_plus'] = (team_league_advanced_df['ts_pct'] / team_league_advanced_df['league_ts_pct']) * 100
team_league_advanced_df['scoring_plus'] = 100 + (0.765 * (team_league_advanced_df["ts_plus"] - 100)) + (0.235 * (team_league_advanced_df["pts_plus"] - 100))

team_league_advanced_df[['team_name', 'season_end_year', 'pts_plus', 'ts_plus', 'scoring_plus']].head(10)

,team_name,season_end_year,pts_plus,ts_plus,scoring_plus
0,Atlanta Hawks,2001,95.416115,96.518671,96.259571
1,Boston Celtics,2001,98.567111,100.572456,100.101200
2,Charlotte Hornets,2001,98.173237,97.676895,97.793536
3,Chicago Bulls,2001,94.431428,95.553485,95.289801
4,Cleveland Cavaliers,2001,97.779362,98.256007,98.143996
5,Dallas Mavericks,2001,103.982887,105.012314,104.770399
6,Denver Nuggets,2001,100.634953,98.642082,99.110407
7,Detroit Pistons,2001,96.991613,96.132597,96.334466
8,Golden State Warriors,2001,94.825303,90.727551,91.690523
9,Houston Rockets,2001,103.589012,103.854090,103.791797

In [7]:
scoring_plus_means = team_league_advanced_df.groupby('season_end_year')[['ts_plus', 'pts_plus', 'scoring_plus']].mean().reset_index()
scoring_plus_means

    season_end_year  ts_plus  pts_plus  scoring_plus
0              2001    100.0     100.0         100.0
1              2002    100.0     100.0         100.0
2              2003    100.0     100.0         100.0
3              2004    100.0     100.0         100.0
4              2005    100.0     100.0         100.0
5              2006    100.0     100.0         100.0
6              2007    100.0     100.0         100.0
7              2008    100.0     100.0         100.0
8              2009    100.0     100.0         100.0
9              2010    100.0     100.0         100.0
10             2011    100.0     100.0         100.0
11             2012    100.0     100.0         100.0
12             2013    100.0     100.0         100.0
13             2014    100.0     100.0         100.0
14             2015    100.0     100.0         100.0
15             2016    100.0     100.0         100.0
16             2017    100.0     100.0         100.0
17             2018    100.0     100.0         100.0
18             2019    100.0     100.0         100.0
19             2020    100.0     100.0         100.0
20             2021    100.0     100.0         100.0
21             2022    100.0     100.0         100.0
22             2023    100.0     100.0         100.0
23             2024    100.0     100.0         100.0
24             2025    100.0     100.0         100.0
25             2026    100.0     100.0         100.0